### ISSUE TITLE
tag sdk-1.2.135?

### ISSUE THREAD

**Issue by tjaalton** [KhronosGroup/Vulkan-Headers#108]
Hi, loader/tools/validationlayers got tagged with sdk-1.2.135 already, shouldn't the headers too?

**Comment by KarenGhavam-lunarG** [comment]
Actually, the loader/tools/validationlayers don't have a tag sdk-1.2.135.  However branches have been created for SDK-1.2.135 because we are in process of preparing an SDK release. 

I am looking at Vulkan-Headers and see a tag: v1.2.135 and also see the SDK branch (sdk-1.2.135). But there aren't any tags sdk-1.2.135

**Comment by tjaalton** [comment]
huh, indeed! 
I'll be more careful when looking around after a git fetch..
