### ISSUE TITLE
Breakage in vulkan-tools and metacity with vulkan-headers-1.2.140

### ISSUE THREAD

**Issue by Cogitri** [KhronosGroup/Vulkan-Headers#117]
Hello,

in vulkan-headers-1.2.140 the definition of `VK_DYNAMIC_STATE_RANGE_SIZE` has been removed, which breaks building packages such as vulkan-tools and metacity (and possibly more). Alpine Linux had to revert back to vulkan-headers-1.2.139 for the time being due to that [0].

0: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/7601

**Comment by oddhack** [comment]
I'm sorry for the breakage. We did the best we knew how reaching out in multiple formats and forums but obviously these projects didn't get the message. Note that these tokens are explicitly not part of the Vulkan API, which is why they were removed.

If you absolutely must have them for some reason then there is a procedure defined in https://github.com/KhronosGroup/Vulkan-Docs/issues/1230 and in the Vulkan-Docs ChangeLog.txt for 1.2.140 telling you how to build headers with these tokens yourself, but we will not be restoring them to the Khronos-supplied headers.

**Comment by oddhack** [comment]
I opened an issue against Vulkan-Tools repo where one use in sample code was overlooked. I don't know anything about metacity and don't have accounts on the relevant git servers, so suggest @Cogitri open an issue there to resolve that problem.

**Comment by Cogitri** [comment]
Alrighty, I'll look into the other projects, thanks.
