### ISSUE TITLE
Documentation error in VkViewport?

### ISSUE THREAD

**Issue by facebamm** [KhronosGroup/Vulkan-Headers#180]
Is it right that the minDepth has to be greater than or equal to maxDepth? 

[VkViewport](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#VkViewport)
"minDepth and maxDepth are the depth range for the viewport. It is valid for minDepth to be greater than or equal to maxDepth."

Found with @baetz-daniel

**Comment by oddhack** [comment]
Would it be more clear if this were put into a NOTE saying something like "despite the names of minDepth and maxDepth, there is no requirement that minDepth be strictly less than maxDepth"?

**Comment by facebamm** [comment]
In my opinion yes, because currently, it says to me that minDepth is only valid if it is greater than or equal to maxDepth.

It would already be enough in my eyes to make this change: "It is valid for minDepth to also be greater than or equal to maxDepth."

**Comment by oddhack** [comment]
This was fixed in the 1.2.171 spec update back in March but I neglected to close this issue at the time. N.b. Vulkan-Headers really isn't a great place to report issues with anything but the repository structure, because it's just a place for collecting various files used by downstream components. Issues with the spec or headers or XML should usually be reported on KhronosGroup/Vulkan-Docs where they are maintained.
