### ISSUE TITLE
Meaning of "bitvalues" in bitmasks?

### ISSUE THREAD

**Issue by osor-io** [KhronosGroup/Vulkan-Headers#185]
Hey! 😄 

I'm parsing vk.xml to do Jai bindings in https://github.com/osor-io/Vulkan. Trying to update to 1.2.170 I found a difference when parsing the bitflags that then reference the enums with the flag bits.

In line 272 and 273 there's `VkAccessFlags2KHR` and `VkPipelineStageFlags2KHR` which instead of using the attribute `requires` to reference the FlagBits enum they use `bitvalues`.

This seems to apparently mean the same in this case, but I wonder if I'm missing some key difference here (besides the fact that they are now 64 bits, which doesn't seem like it should be related).

Am I safe to handle `bitvalues` the same way as `requires` here? If that is a yes, why does it exist?

**Comment by oddhack** [comment]
They are not quite the same. With the syncrhonization2 extension shipping, some of the bitflag types now need to have more than 32 flags, and it's impossible to express that in a portable fashion in C/C++ as members of an enumerated type, since you can't control the underlying integer type of the enumeration. So if you look at the \<enums> entry for VkPipelineStageFlagBits2KHR, it has a 'bitwidth="64"' attribute which causes the generator script to emit these flags as 'static const' values instead of an enumerated type. The gist of the difference is that the bitflags that are defined in enumerated types need to trigger the definition of the enumerated type itself, while those that are defined in static const integers just need to trigger the typedef of VkFlags64 to the flag type.

Arguably it would have been better to use static const flag values from the beginning, but (a) "Nobody will ever need more than 640K" and (b) the enums do provide some typesafety that you don't get with the static const values.

I don't know if the definitions in the registry schema document (https://www.khronos.org/registry/vulkan/specs/1.2/registry.html) is sufficient to document this properly, if not it would be good to get some feedback on what could be better there.

**Comment by osor-io** [comment]
Thanks @oddhack! That does make sense. I had missed the update on the registry too.

Those being the differences it seems like handling them for Jai as I was seems correct. There I can just alias the Flags to the FlagBits enum (which will be defined as 64 bit). And stuff should just work ™️ 

```
VkPipelineStageFlags2KHR :: VkPipelineStageFlagBits2KHR;

VkPipelineStageFlagBits2KHR :: enum_flags u64
{
    VK_PIPELINE_STAGE_2_NONE_KHR :: 0;
    VK_PIPELINE_STAGE_2_TOP_OF_PIPE_BIT_KHR :: (1 << 0);
    // . . . etc . . .
}
```

I'm trying to keep the "Flags" types as an alias of the "FlagBits" enums, since that gives really good type safety in this language, and you get a lot of type information that you can use from this too. An extra nice titbit is that printing one of these flag values will give you the ORed list of flags with the names, instead of just the value.

You can take a look at https://github.com/osor-io/Vulkan/blob/master/vulkan_header.jai if anyone's interested 😄 

Thanks for the help! I'll close this one

**Comment by oddhack** [comment]
> I'm trying to keep the "Flags" types as an alias of the "FlagBits" enums, since that gives really good type safety in this language, and you get a lot of type information that you can use from this too. 

For reference, the FlagBits types are a single bit, while the Flags types are arbitrary combinations of FlagBits. There are a couple of places in the API where we only allow passing a single bit (mutually exclusive), in those cases the passed type is FlagBits instead of Flags. Unfortunately there's no way to really express this semantic relationship in C.
