### ISSUE TITLE
compilation issue under clang + windows

### ISSUE THREAD

**Issue by neheb** [KhronosGroup/Vulkan-Headers#200]
```
C:/msys64/home/Mangix/devstuff/MINGW-packages/mingw-w64-vulkan-loader/src/Vulkan-Loader-1.2.166/loader/trampoline.c:768:42: error: redeclaration of 'vkGetPhysicalDeviceMemoryProperties' cannot add 'dllexport' attribute
LOADER_EXPORT VKAPI_ATTR void VKAPI_CALL vkGetPhysicalDeviceMemoryProperties(VkPhysicalDevice physicalDevice,
                                         ^
C:/msys64/clang64/include/vulkan/vulkan_core.h:3303:28: note: previous declaration is here
VKAPI_ATTR void VKAPI_CALL vkGetPhysicalDeviceMemoryProperties(
                           ^
C:/msys64/home/Mangix/devstuff/MINGW-packages/mingw-w64-vulkan-loader/src/Vulkan-Loader-1.2.166/loader/trampoline.c:776:46: error: redeclaration of 'vkCreateDevice' cannot add 'dllexport' attribute
LOADER_EXPORT VKAPI_ATTR VkResult VKAPI_CALL vkCreateDevice(VkPhysicalDevice physicalDevice, const VkDeviceCreateInfo *pCreateInfo,
                                             ^
C:/msys64/clang64/include/vulkan/vulkan_core.h:3315:32: note: previous declaration is here
VKAPI_ATTR VkResult VKAPI_CALL vkCreateDevice(
```

and many more. The failure happens when compiling vulkan-loader but I think the headers are the problem. They don't add dllexport.

**Comment by osor-io** [comment]
You can define `VK_NO_PROTOTYPES` so `vulkan_core.h` doesn't declare those symbols, and the ones you'll use will be the ones in the loader (with `dllexport`) and you'd avoid the redeclarations.

**Comment by charles-lunarg** [comment]
On windows, the 'default' way of exposing symbols is to add them to the `.def` file when compiling the .dll, which is what the loader currently does. While `dllexport` exists and does export symbols, the reason it isn't used on Windows is because in 32 bit builds, names are still mangled, regardless of what shows up in the headers. For this reason a .def file is required and there are no plans on changing this.
