### ISSUE TITLE
Rust bindings by Khronos

### ISSUE THREAD

**Issue by neurotok** [KhronosGroup/Vulkan-Headers#245]
Rust programming language is getting more and more popular every year. It have fully feature FFI which enables him to connect directly to C headers but I found this approach unnecessary complex and compromising compile time,

There are already vulkan bindings projects like ash or erupt that use vk.xml to auto generate rust interface but I think Khronos itself could come out with something more official. 

Something that could put Rust in the same league as C++. I think it would be a good investment in the future of Vulkan.

**Comment by Friz64** [comment]
Previous discussion: https://github.com/KhronosGroup/Vulkan-Docs/issues/1334

**Comment by oddhack** [comment]
As the discussion on the Vulkan-Docs issue brought up, the community-supported efforts are likely to do a better job and achieve wide use, because they're actually focused on that problem. The Vulkan WG is focused on Vulkan itself.

This is purely a staging repository for collecting generated spec artifacts, so if you want to discuss further, please take it back to the Vulkan-Docs issue. Thanks.
