### ISSUE TITLE
Question: vkGetPhysicalDevicePresentRectanglesKHR always null with vkGetDeviceProcAddr?

### ISSUE THREAD

**Issue by DanielBaumert** [KhronosGroup/Vulkan-Headers#263]
Hello :smile:  

The method ``vkGetPhysicalDevicePresentRectanglesKHR`` is declared below the extension ``VK_KHR_swapchain``(https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_swapchain.html)
and the extension is defined as device extensions.

Now the but:
When I'm trying to load the ``vkGetPhysicalDevicePresentRectanglesKHR``-Proc with ``vkGetDeviceProcAddr`` is the return value always null, that's means to me - function not found.

I played a little bit around and found out: 
When I'm trying to load the ``vkGetPhysicalDevicePresentRectanglesKHR``-Proc with ``vkGetInstanceProcAddr``  is the return value a valid function pointer.

Everything else works below ``VK_KHR_swapchain`` with ``vkGetDeviceProcAddr``.

Question: 
Can I say: ``vkGetInstanceProcAddr`` is a fallback to ``vkGetDeviceProcAddr`` ? (I don't think so) 

Question:
In the documentation is written 'Requires [VK_KHR_surface](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_KHR_surface.html)' and the extension ``VK_KHR_surface`` is market as ``instance extension``.
Is that the reason why I always get zero back with ``vkGetDeviceProcAddr``?

Daniel Baumert

**Comment by charles-lunarg** [comment]
> When I'm trying to load the vkGetPhysicalDevicePresentRectanglesKHR-Proc with vkGetInstanceProcAddr is the return value a valid function pointer.

This is very likely because of the 'unknown physical device function' handling. The function pointer gotten from `vkGetInstanceProcAddr` is available before you create the `VkDevice`, so it is impossible to know whether the function pointer is valid or not yet. Only when you create a VkDevice is that knowable. Thus the loader has to provide a function pointer, and trust that the application doesn't call it.

Some loader docs about this behavior: https://github.com/KhronosGroup/Vulkan-Loader/blob/master/docs/LoaderApplicationInterface.md#unknown-extensions

This is the docs for Loader-Driver interactions, so its a bit more detailed but written for people writing drivers. https://github.com/KhronosGroup/Vulkan-Loader/blob/master/docs/LoaderDriverInterface.md#driver-unknown-physical-device-extensions
