### ISSUE TITLE
vk_enum_string_helper.h missing

### ISSUE THREAD

**Issue by duhone** [KhronosGroup/Vulkan-Headers#414]
**Describe the bug**

The file vk_enum_string_helper.h is missing. It seems like every other file in Include\vulkan from the SDK is here, but not this one. For instance, this forces me to use the full sdk github action instead of the lightweight one, since I depend on that file.

**Expected behavior**
the file vk_enum_string_helper.h is included.

**Comment by StefanG3D** [comment]
Get the raw file from here:
https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/main/layers/vulkan/generated/vk_enum_string_helper.h

**Comment by oddhack** [comment]
@juan-lunarg please advise - I can pull a copy of this from VVL when doing the spec updates, if the link above is the correct source. Best to update everything in the same tagged commit, I think.

**Comment by oddhack** [comment]
Although, since VVL itself does not update until sometime after XML changes are published in Vulkan-Headers, in general anything sourced from there is going to lag the spec update.

**Comment by juan-lunarg** [comment]
> The file vk_enum_string_helper.h is missing. It seems like every other file in Include\vulkan from the SDK is here, but not this one. For instance, this forces me to use the full sdk github action instead of the lightweight one, since I depend on that file.

Vulkan-Headers has never supplied `vk_enum_string_helper.h`. That file currently comes from the vulkan validation layers due to historical reasons.

> Although, since VVL itself does not update until sometime after XML changes are published in Vulkan-Headers, in general anything sourced from there is going to lag the spec update.

Yeah it would end up lagging unless you are willing to generate the code in VVL pointing to the new headers. IE it would make your process more complicated. Also we plan to move `vk_enum_string_helper.h` to the https://github.com/KhronosGroup/Vulkan-Utility-Libraries instead of living in vvl.

**Comment by juan-lunarg** [comment]
https://github.com/KhronosGroup/Vulkan-Utility-Libraries/issues/39
