### ISSUE TITLE
generator.py broken dependencies

### ISSUE THREAD

**Issue by gnl21** [KhronosGroup/Vulkan-Headers#75]
generator.py includes spec_tools.utils, but I can't find that in this repo. It looks like it needs to be synched from the Khronos-private repository.

**Comment by oddhack** [comment]
It's in the public Vulkan-Docs repo, but I'll need to add it to my process for constructing updates to this repo. See https://github.com/KhronosGroup/Vulkan-Docs/tree/master/scripts/spec_tools

**Comment by shannon-lunarg** [comment]
Note: The Loader and ValidationLayers will not be able to take a new header until this issue is fixed.

**Comment by oddhack** [comment]
@gnl21 @shannon-lunarg could you test with #76? I'm unclear on how you're using the scripts so I can't test your scenario. For example, I can't run genvk.py because of the dependency on docgenerator.py, but that situation surely existed before the recent script update that added spec_tools, so I assume you're not using that script.

**Comment by gnl21** [comment]
That works for me (I've left a comment in the PR). Some of the code in our driver is autogenerated using reg.py which includes generator.py and so was failing.
